package com.web.outputservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-01-24T15:55:42.863+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://impl.outputService.web.com/", name = "UserServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://impl.outputService.web.com/", className = "com.web.outputservice.impl.GetPersonById")
    @WebMethod
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://impl.outputService.web.com/", className = "com.web.outputservice.impl.GetPersonByIdResponse")
    public com.web.outputservice.impl.Person getPersonById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
