
package com.web.outputservice.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-01-24T15:55:42.805+08:00
 * Generated source version: 3.1.11
 * 
 */
public final class UserServiceImpl_UserServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.outputService.web.com/", "UserServiceImplService");

    private UserServiceImpl_UserServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserServiceImplService ss = new UserServiceImplService(wsdlURL, SERVICE_NAME);
        UserServiceImpl port = ss.getUserServiceImplPort();  
        
        {
        System.out.println("Invoking getPersonById...");
        int _getPersonById_arg0 = -1729300533;
        com.web.outputservice.impl.Person _getPersonById__return = port.getPersonById(_getPersonById_arg0);
        System.out.println("getPersonById.result=" + _getPersonById__return);


        }

        System.exit(0);
    }

}
