
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.web.outputservice.impl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-01-24T15:55:42.847+08:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserServiceImplService",
                      portName = "UserServiceImplPort",
                      targetNamespace = "http://impl.outputService.web.com/",
                      wsdlLocation = "http://localhost:8080/webServiceTest/webservice/getPersonById?wsdl",
                      endpointInterface = "com.web.outputservice.impl.UserServiceImpl")
                      
public class UserServiceImplPortImpl implements UserServiceImpl {

    private static final Logger LOG = Logger.getLogger(UserServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.web.outputservice.impl.UserServiceImpl#getPersonById(int arg0)*
     */
    public com.web.outputservice.impl.Person getPersonById(int arg0) { 
        LOG.info("Executing operation getPersonById");
        System.out.println(arg0);
        try {
            com.web.outputservice.impl.Person _return = new com.web.outputservice.impl.Person();
            _return.setAge(Integer.valueOf(86890200));
            _return.setId(Integer.valueOf(1126691162));
            _return.setName("Name1502215291");
            _return.setSex("Sex-727585948");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
