package com.web.outputservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-01-24T15:55:42.868+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "UserServiceImplService", 
                  wsdlLocation = "http://localhost:8080/webServiceTest/webservice/getPersonById?wsdl",
                  targetNamespace = "http://impl.outputService.web.com/") 
public class UserServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.outputService.web.com/", "UserServiceImplService");
    public final static QName UserServiceImplPort = new QName("http://impl.outputService.web.com/", "UserServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webServiceTest/webservice/getPersonById?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webServiceTest/webservice/getPersonById?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserServiceImpl
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserServiceImpl getUserServiceImplPort() {
        return super.getPort(UserServiceImplPort, UserServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceImpl
     */
    @WebEndpoint(name = "UserServiceImplPort")
    public UserServiceImpl getUserServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserServiceImplPort, UserServiceImpl.class, features);
    }

}
